(function(){var h={},mt={},c={id:"d8e95c635d8135c55060c556fd69e039",dm:["wbiao.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[{id:"ADart",eventType:"onclick"}],icon:'',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:3618247,qiao:0,lxb:0,conv:0,med:0,cvcc:{id:/wpa|qq_kefu|launchBtn/i,q:/openqq|tencent:\/\/|qq\.(com|htm)/i},cvcf:['__AD_detail_click_17.1'],apps:''};var r=void 0,s=!0,t=null,u=!1;mt.cookie={};mt.cookie.set=function(a,d,b){var e;b.M&&(e=new Date,e.setTime(e.getTime()+b.M));document.cookie=a+"="+d+(b.domain?"; domain="+b.domain:"")+(b.path?"; path="+b.path:"")+(e?"; expires="+e.toGMTString():"")+(b.ub?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:t};mt.f={};mt.f.N=function(a){return document.getElementById(a)};
mt.f.P=function(a,d){var b=[],e=[];if(!a)return e;for(;a.parentNode!=t;){for(var g=0,l=0,m=a.parentNode.childNodes.length,f=0;f<m;f++){var n=a.parentNode.childNodes[f];if(n.nodeName===a.nodeName&&(g++,n===a&&(l=g),0<l&&1<g))break}if((m=""!==a.id)&&d){b.unshift("#"+encodeURIComponent(a.id));break}else m&&(m="#"+encodeURIComponent(a.id),m=0<b.length?m+">"+b.join(">"):m,e.push(m)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<g?"["+l+"]":""));a=a.parentNode}e.push(b.join(">"));return e};
mt.f.Ja=function(a){return(a=mt.f.P(a,s))&&a.length?String(a[0]):""};mt.f.ob=function(a){return mt.f.P(a,u)};mt.f.Ba=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return t};mt.f.Da=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};
mt.f.Ha=function(a){var d=mt.f.Da(a),b={top:0,left:0};if(a)return d=d.documentElement,"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect()),{top:b.top+(window.pageYOffset||d.scrollTop)-(d.clientTop||0),left:b.left+(window.pageXOffset||d.scrollLeft)-(d.clientLeft||0)}};
(mt.f.U=function(){function a(){if(!a.D){a.D=s;for(var d=0,b=e.length;d<b;d++)e[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(d,1);return}a()}var b=u,e=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,u);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!b)if(b=s,"complete"===document.readyState)a.D=s;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
g,u),window.addEventListener("load",a,u);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var e=u;try{e=window.frameElement==t}catch(m){}document.documentElement.doScroll&&e&&d()}})();return function(d){a.D?d():e.push(d)}}()).D=u;mt.event={};mt.event.c=function(a,d,b){a.attachEvent?a.attachEvent("on"+d,function(e){b.call(a,e)}):a.addEventListener&&a.addEventListener(d,b,u)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=u};
(function(){var a=mt.event;mt.k={};mt.k.ca=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.k.Ua=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:r;mt.k.cookieEnabled=navigator.cookieEnabled;mt.k.javaEnabled=navigator.javaEnabled();mt.k.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.k.ab=(window.screen.width||0)+"x"+(window.screen.height||0);mt.k.colorDepth=window.screen.colorDepth||0;mt.k.orientation=0;
(function(){function d(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.k.orientation=a}d();a.c(window,"orientationchange",d)})();return mt.k})();mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var e=b[a];if(e)return e;e=a.charCodeAt();return"\\u00"+Math.floor(e/16).toString(16)+(e%16).toString(16)}));return'"'+a+'"'}function d(a){return 10>a?"0"+a:a}var b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return a(e);case "boolean":return String(e);
default:if(e===t)return"null";if(e instanceof Array){var b=["["],l=e.length,m,f,n;for(f=0;f<l;f++)switch(n=e[f],typeof n){case "undefined":case "function":case "unknown":break;default:m&&b.push(","),b.push(mt.m.stringify(n)),m=1}b.push("]");return b.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+d(e.getMonth()+1)+"-"+d(e.getDate())+"T"+d(e.getHours())+":"+d(e.getMinutes())+":"+d(e.getSeconds())+'"';m=["{"];f=mt.m.stringify;for(l in e)if(Object.prototype.hasOwnProperty.call(e,l))switch(n=
e[l],typeof n){case "undefined":case "unknown":case "function":break;default:b&&m.push(","),b=1,m.push(f(l)+":"+f(n))}m.push("}");return m.join("")}}}();mt.lang={};mt.lang.d=function(a,d){return"[object "+d+"]"==={}.toString.call(a)};mt.lang.qb=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.tb=function(a){return mt.lang.d(a,"String")};mt.lang.i=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.localStorage={};
mt.localStorage.J=function(){if(!mt.localStorage.j)try{mt.localStorage.j=document.createElement("input"),mt.localStorage.j.type="hidden",mt.localStorage.j.style.display="none",mt.localStorage.j.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.j)}catch(a){return u}return s};
mt.localStorage.set=function(a,d,b){var e=new Date;e.setTime(e.getTime()+b||31536E6);try{window.localStorage?(d=e.getTime()+"|"+d,window.localStorage.setItem(a,d)):mt.localStorage.J()&&(mt.localStorage.j.expires=e.toUTCString(),mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.setAttribute(a,d),mt.localStorage.j.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var d=a.indexOf("|"),b=a.substring(0,d)-0;if(b&&b>(new Date).getTime())return a.substring(d+1)}}else if(mt.localStorage.J())try{return mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.getAttribute(a)}catch(e){}return t};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.J())try{mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.removeAttribute(a),mt.localStorage.j.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(b){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):t};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.ga={};mt.ga.log=function(a,d){var b=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=t;b=window[e]=t;d&&d(a)};b.src=a};mt.I={};
mt.I.La=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(a=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=d.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(b){}return a};
mt.I.ua=function(a,d,b,e,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+b+'" height="'+e+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+b+'" height="'+e+'" src="'+d+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.g=function(a,d){var b=a.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return b?b[3]:t};mt.url.pb=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:t};mt.url.Fa=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):t};mt.url.aa=function(a){return(a=mt.url.Fa(a))?a.replace(/:\d+$/,""):a};mt.url.P=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function a(){for(var a=u,b=document.getElementsByTagName("script"),e=b.length,e=100<e?100:e,g=0;g<e;g++){var l=b[g].src;if(l&&0===l.indexOf("https://hm.baidu.com/h")){a=s;break}}return a}return h.Aa=a})();var y=h.Aa;
h.l={Ta:"http://tongji.baidu.com/hm-web/welcome/ico",T:"hm.baidu.com/hm.gif",na:"baidu.com",Qa:"hmmd",Ra:"hmpl",jb:"utm_medium",Pa:"hmkw",mb:"utm_term",Na:"hmci",ib:"utm_content",Sa:"hmsr",lb:"utm_source",Oa:"hmcu",hb:"utm_campaign",z:0,o:Math.round(+new Date/1E3),Y:Math.round(+new Date/1E3)%65535,protocol:"https:"===document.location.protocol?"https:":"http:",F:y()||"https:"===document.location.protocol?"https:":"http:",rb:0,sa:6E5,ta:5,X:1024,ra:1,w:2147483647,ha:"cc cf ci ck cl cm cp cu cw ds ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt".split(" ")};
(function(){var a={s:{},c:function(a,b){this.s[a]=this.s[a]||[];this.s[a].push(b)},B:function(a,b){this.s[a]=this.s[a]||[];for(var e=this.s[a].length,g=0;g<e;g++)this.s[a][g](b)}};return h.p=a})();
(function(){function a(a,e){var g=document.createElement("script");g.charset="utf-8";d.d(e,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=t,e()}:g.onload=function(){e()});g.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(g,l)}var d=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?b.set("Hm_from_"+c.id,a):d.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?b.get("Hm_from_"+c.id):d.get("Hm_from_"+c.id))||"";return a}var d=mt.localStorage,b=mt.sessionStorage;return h.Z=a})();
(function(){var a=h.l,d=mt.I,b={init:function(){if(""!==c.icon){var e;e=c.icon.split("|");var b=a.Ta+"?s="+c.id,l=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+e[0]+"."+e[1];switch(e[1]){case "swf":e=d.ua("HolmesIcon"+a.o,l,e[2],e[3],"s="+b);break;case "gif":e='<a href="'+b+'" target="_blank"><img border="0" src="'+l+'" width="'+e[2]+'" height="'+e[3]+'"></a>';break;default:e='<a href="'+b+'" target="_blank">'+e[0]+"</a>"}document.write(e)}}};h.p.c("pv-b",b.init);return b})();
(function(){var a=mt.f,d=mt.event,b={ka:function(){d.c(document,"click",b.xa());for(var e=c.etrk.length,g=0;g<e;g++){var l=c.etrk[g],m=a.N(decodeURIComponent(l.id));m&&d.c(m,l.eventType,b.L())}},L:function(){return function(a){(a.target||a.srcElement).setAttribute("HM_fix",a.clientX+":"+a.clientY);h.b.a.et=1;h.b.a.ep="{id:"+this.id+",eventType:"+a.type+"}";h.b.h()}},xa:function(){return function(a){var b=a.target||a.srcElement;if(b){var d=b.getAttribute("HM_fix"),m=a.clientX+":"+a.clientY;if(d&&d==
m)b.removeAttribute("HM_fix");else if(d=c.etrk.length,0<d){for(m={};b&&b!=document.body;)b.id&&(m[b.id]=""),b=b.parentNode;for(b=0;b<d;b++){var f=decodeURIComponent(c.etrk[b].id);m.hasOwnProperty(f)&&(h.b.a.et=1,h.b.a.ep="{id:"+f+",eventType:"+a.type+"}",h.b.h())}}}}}};h.p.c("pv-b",b.ka);return b})();
(function(){var a=mt.f,d=mt.lang,b=mt.event,e=mt.k,g=h.l,l=[],m={ia:function(){c.ctrk&&(b.c(document,"mouseup",m.qa()),b.c(window,"unload",function(){m.G()}),setInterval(function(){m.G()},g.sa))},qa:function(){return function(a){a=m.Ca(a);if(""!==a){var n=(g.F+"//"+g.T+"?"+h.b.fa().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;n+(g.w+"").length>g.X||(n+encodeURIComponent(l.join("!")+(l.length?"!":"")).length+(g.w+"").length>g.X&&m.G(),l.push(a),(l.length>=g.ta||/\*a\*/.test(a))&&m.G())}}},
Ca:function(b){var n=b.target||b.srcElement;if(0===g.ra){var k=(n.tagName||"").toLowerCase();if("embed"==k||"object"==k)return""}var v;e.ca?(v=Math.max(document.documentElement.scrollTop,document.body.scrollTop),k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),k=b.clientX+k,v=b.clientY+v):(k=b.pageX,v=b.pageY);b=m.Ga(b,n,k,v);var p=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:k-=p/2;break;case 2:k-=p}p=[];p.push(k);
p.push(v);p.push(b.Wa);p.push(b.Xa);p.push(b.Za);p.push(d.i(b.Ya));p.push(b.nb);p.push(b.Ma);(n="a"===(n.tagName||"").toLowerCase()?n:a.Ba(n))?(p.push("a"),p.push(d.i(encodeURIComponent(n.href)))):p.push("b");return p.join("*")},Ga:function(b,n,k,d){b=a.Ja(n);var p=0,q=0,g=0,w=0;if(n&&(p=n.offsetWidth||n.clientWidth,q=n.offsetHeight||n.clientHeight,w=a.Ha(n),g=w.left,w=w.top,"html"===(n.tagName||"").toLowerCase()))p=Math.max(p,n.clientWidth),q=Math.max(q,n.clientHeight);return{Wa:Math.round(100*((k-
g)/p)),Xa:Math.round(100*((d-w)/q)),Za:e.orientation,Ya:b,nb:p,Ma:q}},G:function(){0!==l.length&&(h.b.a.et=2,h.b.a.ep=l.join("!"),h.b.h(),l=[])}};h.p.c("pv-b",m.ia);return m})();
(function(){var a=mt.f,d=h.l,b=h.load,e=h.Z;h.p.c("pv-b",function(){var g=d.protocol+"//crs.baidu.com/";c.rec&&a.U(function(){for(var l=0,m=c.rp.length;l<m;l++){var f=c.rp[l][0],n=c.rp[l][1],k=a.N("hm_t_"+f);if(n&&!(2==n&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*d.w),k=4==n?g+"hl.js?"+["siteId="+c.id,"planId="+f,"rnd="+k].join("&"):g+"t.js?"+["siteId="+c.id,"planId="+f,"from="+e(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+k].join("&"),
b(k)}})})})();(function(){var a=h.l,d=h.load,b=h.Z;h.p.c("pv-b",function(){if(c.trust&&c.vcard){var e="https://tag.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+b(),"rnd="+Math.round(Math.random()*a.w),"hm=1"].join("&");d(e)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.K.Ia()+","+h.K.Ea();h.b.h()}}function d(){clearTimeout(B);var a;w&&(a="visible"==document[w]);C&&(a=!document[C]);f="undefined"==typeof a?s:a;if((!m||!n)&&f&&k)x=s,p=+new Date;else if(m&&n&&(!f||!k))x=u,q+=+new Date-p;m=f;n=k;B=setTimeout(d,100)}function b(a){var n=document,p="";if(a in n)p=a;else for(var b=["webkit","ms","moz","o"],k=0;k<b.length;k++){var d=b[k]+a.charAt(0).toUpperCase()+a.slice(1);if(d in n){p=
d;break}}return p}function e(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))k="focus"==a.type||"focusin"==a.type?s:u,d()}var g=mt.event,l=h.p,m=s,f=s,n=s,k=s,v=+new Date,p=v,q=0,x=s,w=b("visibilityState"),C=b("hidden"),B;d();(function(){var a=w.replace(/[vV]isibilityState/,"visibilitychange");g.c(document,a,d);g.c(window,"pageshow",d);g.c(window,"pagehide",d);"object"==typeof document.onfocusin?(g.c(document,"focusin",e),g.c(document,"focusout",e)):(g.c(window,"focus",e),
g.c(window,"blur",e))})();h.K={Ia:function(){return+new Date-v},Ea:function(){return x?+new Date-p+q:q}};l.c("pv-b",function(){g.c(window,"unload",a())});return h.K})();
(function(){var a=mt.lang,d=h.l,b=h.load,e={Va:function(e){if((window._dxt===r||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var l=h.b.O();b([d.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),e)}},gb:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.va=e})();
(function(){function a(a,b,d,p){if(!(a===r||b===r||p===r)){if(""===a)return[b,d,p].join("*");a=String(a).split("!");for(var e,f=u,g=0;g<a.length;g++)if(e=a[g].split("*"),String(b)===e[0]){e[1]=d;e[2]=p;a[g]=e.join("*");f=s;break}f||a.push([b,d,p].join("*"));return a.join("!")}}function d(a){for(var k in a)if({}.hasOwnProperty.call(a,k)){var e=a[k];b.d(e,"Object")||b.d(e,"Array")?d(e):a[k]=String(e)}}var b=mt.lang,e=mt.m,g=h.l,l=h.p,m=h.va,f={A:[],H:0,da:u,r:{W:"",page:""},init:function(){f.e=0;l.c("pv-b",
function(){f.wa();f.ya()});l.c("pv-d",function(){f.za();f.r.page=""});l.c("stag-b",function(){h.b.a.api=f.e||f.H?f.e+"_"+f.H:"";h.b.a.ct=[decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),f.r.W,f.r.page].join("!")});l.c("stag-d",function(){h.b.a.api=0;f.e=0;f.H=0})},wa:function(){var a=window._hmt||[];if(!a||b.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,n=0;n<arguments.length;n++){var p=arguments[n];b.d(p,"Array")&&(a.cmd[a.id].push(p),"_setAccount"===p[0]&&(1<
p.length&&/^[0-9a-f]{32}$/.test(p[1]))&&(p=p[1],a.id=p,a.cmd[p]=a.cmd[p]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},ya:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,p=0,e=b.length;p<e;p++){var g=b[p];d.test(g[0])?f.A.push(g):f.S(g)}a.cmd[c.id]={push:f.S}},za:function(){if(0<f.A.length)for(var a=0,b=f.A.length;a<b;a++)f.S(f.A[a]);f.A=t},S:function(a){var d=a[0];if(f.hasOwnProperty(d)&&b.d(f[d],"Function"))f[d](a)},
_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(f.e|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],u===a||s===a))f.e|=2,h.b.ba=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){f.e|=4;h.b.a.et=0;h.b.a.ep="";h.b.Q?(h.b.a.nv=0,h.b.a.st=4):h.b.Q=s;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=g.protocol+"//"+document.location.host+a[1];f.da||(h.b.a.su=document.location.href);h.b.h();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(f.e|=8,h.b.a.nv=
0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b.i(a[1])+"*"+b.i(a[2])+(a[3]?"*"+b.i(a[3]):"")+(a[4]?"*"+b.i(a[4]):""),h.b.h())},_setCustomVar:function(a){if(!(4>a.length)){var d=a[1],e=a[4]||3;if(0<d&&6>d&&0<e&&4>e){f.H++;for(var p=(h.b.a.cv||"*").split("!"),q=p.length;q<d-1;q++)p.push("*");p[d-1]=e+"*"+b.i(a[2])+"*"+b.i(a[3]);h.b.a.cv=p.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.$a("Hm_cv_"+c.id)}}},_setUserTag:function(d){if(!(3>
d.length)){var e=b.i(d[1]);d=b.i(d[2]);if(e!==r&&d!==r){var f=decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),f=a(f,e,1,d);h.b.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(d){if(!(3>d.length)){var e=b.i(d[1]);d=b.i(d[2]);if(e!==r&&d!==r){var g=f.r.W,g=a(g,e,2,d);f.r.W=g}}},_setPageTag:function(d){if(!(3>d.length)){var e=b.i(d[1]);d=b.i(d[2]);if(e!==r&&d!==r){var g=f.r.page,g=a(g,e,3,d);f.r.page=g}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&
"/"===a[1].charAt(0)?g.protocol+"//"+window.location.host+a[1]:a[1],f.da=s)},_trackOrder:function(a){a=a[1];b.d(a,"Object")&&(d(a),f.e|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=e.stringify(a),h.b.h())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])f.e|=32,h.b.a.et=93,h.b.a.ep=a,h.b.h()},_trackRTPageview:function(a){a=a[1];b.d(a,"Object")&&(d(a),a=e.stringify(a),512>=encodeURIComponent(a).length&&(f.e|=64,h.b.a.rt=a))},_trackRTEvent:function(a){a=a[1];if(b.d(a,
"Object")){d(a);a=encodeURIComponent(e.stringify(a));var k=function(a){var b=h.b.a.rt;f.e|=128;h.b.a.et=90;h.b.a.rt=a;h.b.h();h.b.a.rt=b},m=a.length;if(900>=m)k.call(this,a);else for(var m=Math.ceil(m/900),p="block|"+Math.round(Math.random()*g.w).toString(16)+"|"+m+"|",q=[],l=0;l<m;l++)q.push(l),q.push(a.substring(900*l,900*l+900)),k.call(this,p+q.join("|")),q=[]}},_setUserId:function(a){a=a[1];m.Va();m.gb(a)}};f.init();h.oa=f;return h.oa})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=s,this.a={},this.ba=s,this.Q=u,this.init())}var d=mt.url,b=mt.ga,e=mt.I,g=mt.lang,l=mt.cookie,m=mt.k,f=mt.localStorage,n=mt.sessionStorage,k=h.l,v=h.p;a.prototype={R:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ea:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},C:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.ea(a,c.dm[b]))return s}else{var e=d.aa(a);if(e&&this.R(e,c.dm[b]))return s}return u},O:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.R(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},$:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ea(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},Ka:function(){if(!document.referrer)return k.o-k.z>c.vdur?1:4;
var a=u;this.C(document.referrer)&&this.C(document.location.href)?a=s:(a=d.aa(document.referrer),a=this.R(a||"",document.location.hostname));return a?k.o-k.z>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||n.get(a)||f.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.O(),path:this.$(),M:d}),d?f.set(a,b,d):n.set(a,b)}catch(e){}},$a:function(a){try{l.set(a,"",{domain:this.O(),path:this.$(),M:-1}),n.remove(a),f.remove(a)}catch(b){}},eb:function(){var a,b,d,e,g;k.z=this.getData("Hm_lpvt_"+
c.id)||0;13===k.z.length&&(k.z=Math.round(k.z/1E3));b=this.Ka();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(g=e.length-1;0<=g;g--)13===e[g].length&&(e[g]=""+Math.round(e[g]/1E3));for(;2592E3<k.o-e[0];)e.shift();g=4>e.length?2:3;for(1===a&&e.push(k.o);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.o,e="",g=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,k.o);d=k.o===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.C(document.location.href)&&
(""===document.referrer||this.C(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=g},fa:function(){for(var a=[],b=this.a.et,d=0,e=k.ha.length;d<e;d++){var g=k.ha[d],f=this.a[g];"undefined"!==typeof f&&""!==f&&("tt"!==g||"tt"===g&&0===b)&&("ct"!==g||"ct"===g&&0===b)&&a.push(g+"="+encodeURIComponent(f))}switch(b){case 0:a.push("sn="+k.Y);this.a.rt&&a.push("rt="+encodeURIComponent(this.a.rt));break;case 3:a.push("sn="+k.Y);break;case 90:this.a.rt&&a.push("rt="+this.a.rt)}return a.join("&")},
fb:function(){this.eb();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=m.ab;this.a.cl=m.colorDepth+"-bit";this.a.ln=String(m.language).toLowerCase();this.a.ja=m.javaEnabled?1:0;this.a.ck=m.cookieEnabled?1:0;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=e.La();this.a.v="1.2.23";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.a.tt=document.title||"";var a=document.location.href;this.a.cm=d.g(a,k.Qa)||"";this.a.cp=d.g(a,k.Ra)||d.g(a,k.jb)||"";this.a.cw=d.g(a,k.Pa)||d.g(a,
k.mb)||"";this.a.ci=d.g(a,k.Na)||d.g(a,k.ib)||"";this.a.cf=d.g(a,k.Sa)||d.g(a,k.lb)||"";this.a.cu=d.g(a,k.Oa)||d.g(a,k.hb)||""},init:function(){try{this.fb(),0===this.a.nv?this.cb():this.V(".*"),h.b=this,this.pa(),v.B("pv-b"),this.bb()}catch(a){var d=[];d.push("si="+c.id);d.push("n="+encodeURIComponent(a.name));d.push("m="+encodeURIComponent(a.message));d.push("r="+encodeURIComponent(document.referrer));b.log(k.F+"//"+k.T+"?"+d.join("&"))}},bb:function(){function a(){v.B("pv-d")}this.ba?(this.Q=s,
this.a.et=0,this.a.ep="",this.h(a)):a()},h:function(a){var d=this;d.a.rnd=Math.round(Math.random()*k.w);v.B("stag-b");var e=k.F+"//"+k.T+"?"+d.fa();v.B("stag-d");d.ma(e);b.log(e,function(b){d.V(b);g.d(a,"Function")&&a.call(d)})},pa:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),e=-1<document.referrer.indexOf(k.na),g=d.g(a,"jn"),f=/^heatlink$|^select$|^pageclick$/.test(g);a&&(b.test(a)&&e&&f)&&(this.a.rnd=Math.round(Math.random()*k.w),a=document.createElement("script"),a.setAttribute("type",
"text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+g+".js?"+this.a.rnd),g=document.getElementsByTagName("script")[0],g.parentNode.insertBefore(a,g))},ma:function(a){var b=n.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");n.set("Hm_unsent_"+c.id,b)},V:function(a){var b=n.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),
a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?n.set("Hm_unsent_"+c.id,b):n.remove("Hm_unsent_"+c.id))},cb:function(){var a=this,d=n.get("Hm_unsent_"+c.id);if(d)for(var d=d.split(","),e=function(d){b.log(k.F+"//"+decodeURIComponent(d),function(b){a.V(b)})},g=0,f=d.length;g<f;g++)e(d[g])}};return new a})();var z=h.l,A=h.load;if(c.apps){var D=[z.protocol,"//ers.baidu.com/app/s.js?"];D.push(c.apps);A(D.join(""))}var E=h.l,F=h.load;
c.lxb&&F([E.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var G=h.load,H=h.l.protocol;if(c.qiao){for(var I=[H+"//goutong.baidu.com/site/"],J=c.id,K=5381,L=J.length,M=0;M<L;M++)K=(33*K+Number(J.charCodeAt(M)))%4294967296;2147483648<K&&(K-=2147483648);I.push(K%1E3+"/");I.push(c.id+"/b.js");I.push("?siteId="+c.qiao);G(I.join(""))}
(function(){var a=mt.f,d=mt.event,b=mt.url,e=mt.m;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var g=+new Date,l=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},m=t;a.U(function(){m=+new Date});var f=function(){var a,d,f;f=l("navigation");d=l("request");f={netAll:d.start-f.start,netDns:l("domainLookup").value,netTcp:l("connect").value,srv:l("response").start-d.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:l("loadEvent").end-f.start};a=document.referrer;var n=a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[],x=t;d=t;if("www.baidu.com"===n[2]||"m.baidu.com"===n[2])x=b.g(a,"qid"),d=b.g(a,"click_t");a=x;f.qid=a!=t?a:"";d!=t?(f.bdDom=m?m-d:0,f.bdRun=g-d,f.bdDef=l("navigation").start-d):(f.bdDom=0,f.bdRun=0,f.bdDef=0);h.b.a.et=87;h.b.a.ep=e.stringify(f);h.b.h()};d.c(window,"load",function(){setTimeout(f,500)})}}catch(n){}})();
(function(){var a=mt.k,d=mt.lang,b=mt.event,e=mt.m;if("undefined"!==typeof h.b&&(c.med||(!a.ca||7<a.Ua)&&c.cvcc)){var g,l,m,f,n=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},k=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===u)return u},v=function(a,b){var f={};f.n=g;f.t="clk";f.v=a;if(b){var k=b.getAttribute("href"),l=b.getAttribute("onclick")?""+b.getAttribute("onclick"):t,n=b.getAttribute("id")||"";m.test(k)?(f.sn="mediate",
f.snv=k):d.d(l,"String")&&m.test(l)&&(f.sn="wrap",f.snv=l);f.id=n}h.b.a.et=86;h.b.a.ep=e.stringify(f);h.b.h();for(f=+new Date;400>=+new Date-f;);};if(c.med)l="/zoosnet",g="swt",m=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,f={click:function(){for(var a=[],b=n(document.getElementsByTagName("a")),b=[].concat.apply(b,n(document.getElementsByTagName("area"))),b=[].concat.apply(b,n(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(m.test(e)||m.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){l="/other-comm";g="other";m=c.cvcc.q||r;var p=c.cvcc.id||r;f={click:function(){for(var a=[],b=n(document.getElementsByTagName("a")),b=[].concat.apply(b,n(document.getElementsByTagName("area"))),b=[].concat.apply(b,n(document.getElementsByTagName("img"))),d,e,f,g=0,k=b.length;g<k;g++)d=b[g],m!==r?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),p?(d=d.getAttribute("id"),(m.test(e)||m.test(f)||p.test(d))&&
a.push(b[g])):(m.test(e)||m.test(f))&&a.push(b[g])):p!==r&&(d=d.getAttribute("id"),p.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof f&&"undefined"!==typeof m){var q;l+=/\/$/.test(l)?"":"/";var x=function(a,b){if(q===b)return v(l+a,b),u;if(d.d(b,"Array")||d.d(b,"NodeList"))for(var e=0,f=b.length;e<f;e++)if(q===b[e])return v(l+a+"/"+(e+1),b[e]),u};b.c(document,"mousedown",function(a){a=a||window.event;q=a.target||a.srcElement;var b={};for(k(f,function(a,e){b[a]=d.d(e,"Function")?e():document.getElementById(e)});q&&
q!==document&&k(b,x)!==u;)q=q.parentNode})}}})();(function(){var a=mt.f,d=mt.lang,b=mt.event,e=mt.m;if("undefined"!==typeof h.b&&d.d(c.cvcf,"Array")&&0<c.cvcf.length){var g={la:function(){for(var d=c.cvcf.length,e,f=0;f<d;f++)(e=a.N(decodeURIComponent(c.cvcf[f])))&&b.c(e,"click",g.L())},L:function(){return function(){h.b.a.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.a.ep=e.stringify(a);h.b.h()}}};a.U(function(){g.la()})}})();
(function(){var a=mt.event,d=mt.m;if(c.med&&"undefined"!==typeof h.b){var b=+new Date,e={n:"anti",sb:0,kb:0,clk:0},g=function(){h.b.a.et=86;h.b.a.ep=d.stringify(e);h.b.h()};a.c(document,"click",function(){e.clk++});a.c(document,"keyup",function(){e.kb=1});a.c(window,"scroll",function(){e.sb++});a.c(window,"unload",function(){e.t=+new Date-b;g()});a.c(window,"load",function(){setTimeout(g,5E3)})}})();})();
